---
- hosts: local
  remote_user: stefan
  tasks:

  - name: Switch to NVidia graphics
    command: prime-select nvidia
    become: true
    become_method: sudo

  - name: restart bumblebeed
    service:
      name: bumblebeed
      state: restarted
    become: true
    become_method: sudo

  - name: restart X server
    service:
      name: lightdm
      state: restarted
    become: true
    become_method: sudo

