---
- hosts: local
  remote_user: stefan
  tasks:
  - name: Set Nvidia driver version
    set_fact:
      nvdrvvers: 375

  - name: Switch to Intel graphics
    command: prime-select intel
    become: true

  - name: Add Bumblebee testing package repo
    apt_repository:
      repo: 'ppa:bumblebee/testing' 
    become: true

  - name: Uninstall Bumblebee testing 
    apt: name={{ item }} state=absent
    with_items:
      - bumblebee
    become: true

  - name: Blacklist nvidia-driver
    blockinfile:
      dest: /etc/modprobe.d/bumblebee.conf
      block: |
        # blacklist nvidia-{{ nvdrvvers }}
        # blacklist nvidia-{{ nvdrvvers }}-updates
        # blacklist nvidia-experimental-{{ nvdrvvers }}
    become: true




                           
    
