---
- hosts: local
  remote_user: stefan
  tasks:
  - name: Set Nvidia driver version
    set_fact:
      nvdrvvers: 375

  - name: Switch to Intel graphics
    command: prime-select intel
    become: true

  - name: Add Bumblebee testing package repo
    apt_repository:
      repo: 'ppa:bumblebee/testing' 
      state: present
      update_cache: yes
    become: true

  - name: Uninstall old Bumblebee
    apt: name={{ item }} state=removed
    with_items:
      - bumblebee
    become: true

  - name: Install Bumblebee testing 
    apt: 
      name: '{{ item }}'
      state: latest
      force: yes
    with_items:
      - bumblebee
    become: true

  - name: Blacklist nvidia-driver
    blockinfile:
      dest: /etc/modprobe.d/bumblebee.conf
      block: |
        blacklist nvidia-{{ nvdrvvers }}
        blacklist nvidia-{{ nvdrvvers }}-updates
        blacklist nvidia-experimental-{{ nvdrvvers }}
    become: true

  - name: Configure Bumblebee - use nvidia propretary driver
    ini_file:
      dest: /etc/bumblebee/bumblebee.conf
      section: 'bumblebeed'
      option: 'Driver'
      value: 'nvidia'
    become: true

  - name: Configure Bumblebee - specify nvidia driver version {{ nvdrvvers }}
    ini_file:
      dest: /etc/bumblebee/bumblebee.conf
      section: 'driver-nvidia'
      option: 'KernelDriver'
      value: 'nvidia-{{ nvdrvvers }}'
    become: true

  - name: Configure Bumblebee - set nvidia driver library path
    ini_file:
      dest: /etc/bumblebee/bumblebee.conf
      section: 'driver-nvidia'
      option: 'LibraryPath'
      value: '/usr/lib/nvidia-{{ nvdrvvers }}:/usr/lib32/nvidia-{{ nvdrvvers }}'
    become: true

  - name: Configure Bumblebee - set XorgModulePath
    ini_file:
      dest: /etc/bumblebee/bumblebee.conf
      section: 'driver-nvidia'
      option: 'XorgModulePath'
      value: '/usr/lib/nvidia-{{ nvdrvvers }}/xorg,/usr/lib/xorg/modules'
    become: true

  - name: update-alternatives
    alternatives:
      name: x86_64-linux-gnu_gl_conf
      path: /usr/lib/nvidia-{{ nvdrvvers }}-prime/ld.so.conf 

  - name: bumblebeed restart
    systemd:
      name: bumblebeed
      state: restarted
    become: true


                           
    
